import { Ruwudu, Signika, Mulish } from 'next/font/google';
import "./globals.css";

// 1. IMPORTAMOS TUS COMPONENTES DE HEADER Y FOOTER
// (Asegúrate de usar la ruta correcta donde estén tus archivos Header y Footer)
import Header from "./componentes/Header";
import Footer from "./componentes/Footer";

const ruwudu = Ruwudu({
  subsets: ['latin'], // Especifica los subconjuntos de caracteres que necesitas
  weight: '700', // Peso para H1
  variable: '--font-ruwudu', // Define una variable CSS
  display: 'swap', // Estrategia de carga
});

// 2. Configurar Signika (para H2) - Google Font
const signika = Signika({
  subsets: ['latin'],
  weight: '600', // Peso para H2
  variable: '--font-signika', // Variable CSS
  display: 'swap',
});

// 3. Configurar Mulish (para H3 y base font) - Google Font
const mulish = Mulish({
  subsets: ['latin'],
  weights: ['400', '600'], // Especifica los pesos que necesitas (400 para base, 600 para H3)
  variable: '--font-mulish', // Variable CSS
  display: 'swap',
});

export const metadata = {
  title: "Sintergia",
  description: "Generated by jesusfelipeb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* 
        2. Agregamos clases de Tailwind para que el body sea un contenedor flex 
        y ocupe toda la altura de la ventana:
          - flex flex-col: ordena los elementos en columna
          - min-h-screen: ocupa al menos la altura total de la pantalla
          - m-0 p-0: elimina márgenes y paddings por defecto 
      */}
      <body className={`${mulish.variable} ${ruwudu.variable} ${signika.variable} antialiased flex flex-col min-h-screen m-0 p-0`}>
        {/* 3. AGREGAMOS EL HEADER AL INICIO */}
        <Header />

        {/* 
          4. AQUI SE RENDERIZAN LAS DIFERENTES PÁGINAS (children)
          Agregamos 'flex-grow' para que este contenedor
          empuje el footer al final de la página.
        */}
        <main className="flex-grow bg-[#fffafa] -z-50">
          {children}
        </main>

        {/* 5. AGREGAMOS EL FOOTER AL FINAL */}
        <Footer />
      </body>
    </html>
  );
}

