import { Ruwudu, Signika, Mulish } from 'next/font/google';
import "./globals.css";

// 1. IMPORTAMOS TUS COMPONENTES DE HEADER Y FOOTER
// (Asegúrate de usar la ruta correcta donde estén tus archivos Header y Footer)
import Header from "../componentes/Header";
import Footer from "../componentes/Footer";

const ruwudu = Ruwudu({
  subsets: ['latin'], // Especifica los subconjuntos de caracteres que necesitas
  weight: '700', // Peso para H1
  variable: '--font-ruwudu', // Define una variable CSS
  display: 'swap', // Estrategia de carga
});

// 2. Configurar Signika (para H2) - Google Font
const signika = Signika({
  subsets: ['latin'],
  weight: '600', // Peso para H2
  variable: '--font-signika', // Variable CSS
  display: 'swap',
});

// 3. Configurar Mulish (para H3 y base font) - Google Font
const mulish = Mulish({
  subsets: ['latin'],
  weights: ['400', '600'], // Especifica los pesos que necesitas (400 para base, 600 para H3)
  variable: '--font-mulish', // Variable CSS
  display: 'swap',
});

export const metadata = {
  title: "Sintergia",
  description: "Generated by jesusfelipeb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* El body es el contenedor flex principal que gestiona la altura */}
      <body className={`${mulish.variable} ${ruwudu.variable} ${signika.variable} antialiased flex flex-col min-h-screen m-0 p-0`}>

        {/* Contenedor del Video de Fondo Global */}
        {/* Posicionado fijo para cubrir toda la ventana gráfica, z-index muy bajo para estar detrás de todo */}
        {/* overflow-hidden para evitar barras de scroll si el video es ligeramente más grande que la ventana */}
        <div className="fixed inset-0 -z-20 overflow-hidden"> {/* z-index -20 para asegurar que esté bien al fondo */}
          {/* Elemento de Video HTML5 */}
          <video
            autoPlay      // Inicia la reproducción automáticamente
            loop          // Reproduce en bucle continuo
            muted         // Sin sonido (esencial para que autoPlay funcione en la mayoría de navegadores sin interacción del usuario)
            playsInline   // Importante para reproducción en línea en dispositivos móviles
            className="object-cover w-full h-full" // Cubre el área del contenedor manteniendo la relación de aspecto
          >
            {/* Etiqueta <source> para especificar el archivo de video */}
            {/* **¡IMPORTANTE! Reemplaza la ruta '/videos/global-background.mp4'** con la ruta real de tu archivo de video
               dentro de la carpeta `public` de tu proyecto.
               Asegúrate también de que el `type` sea correcto para el formato de tu video (ej: 'video/mp4', 'video/webm').
            */}
            <source src="/bgvideo3.mp4" type="video/mp4" /> {/* <-- REEMPLAZA ESTA LÍNEA */}
            {/* Texto de fallback para navegadores que no soportan el elemento <video> */}
            Tu navegador no soporta el elemento de video.
          </video>
        </div>

        {/* Overlay Global sobre el Video */}
        {/* Posicionado fijo, cubre toda la ventana, z-index bajo (entre el video y el contenido) */}
        {/* bg-black con una opacidad ajustada. Ajusta la opacidad (`opacity-50`) según qué tan oscuro quieras el fondo. */}
        <div className="fixed inset-0 bg-black opacity-30 -z-10"> {/* <-- Ajusta la opacidad si es necesario */}</div> {/* z-index -10 para estar sobre el video pero debajo del contenido */}

        {/* Contenido Principal de la Página (Header, Contenido de las secciones, Footer) */}
        {/* Estos elementos tendrán un z-index por defecto (0) o superior, colocándolos automáticamente por encima del fondo y el overlay con z-index negativo. */}

        <Header />

        {/* Contenedor <main> donde se renderizan las secciones específicas de la página */}
        {/* **Eliminamos el color de fondo bg-[#fffafa]** para que el video de fondo sea visible detrás de las secciones,
           a menos que las secciones mismas tengan su propio color de fondo.
           Si algunas secciones necesitan un fondo sólido, mantén el fondo en esas secciones específicas.
        */}
        <main className="flex-grow"> {/* <-- Eliminado bg-[#fffafa] */}
          {children} {/* Aquí se renderiza el contenido de cada página (tus secciones Hero, Services, etc.) */}
        </main>

        <Footer />

      </body>
    </html>
  );
}

