import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 1. IMPORTAMOS TUS COMPONENTES DE HEADER Y FOOTER
// (Asegúrate de usar la ruta correcta donde estén tus archivos Header y Footer)
import Header from "./componentes/Header";
import Footer from "./componentes/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sintergia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 
        2. Agregamos clases de Tailwind para que el body sea un contenedor flex 
        y ocupe toda la altura de la ventana:
          - flex flex-col: ordena los elementos en columna
          - min-h-screen: ocupa al menos la altura total de la pantalla
          - m-0 p-0: elimina márgenes y paddings por defecto 
      */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen m-0 p-0`}>
        {/* 3. AGREGAMOS EL HEADER AL INICIO */}
        <Header />

        {/* 
          4. AQUI SE RENDERIZAN LAS DIFERENTES PÁGINAS (children)
          Agregamos 'flex-grow' para que este contenedor
          empuje el footer al final de la página.
        */}
        <main className="flex-grow bg-white">
          {children}
        </main>

        {/* 5. AGREGAMOS EL FOOTER AL FINAL */}
        <Footer />
      </body>
    </html>
  );
}

